export const iconList: string[] = [
  'shield-outline', 'arm-flex-outline', 'sword-cross', 'hammer',
  'wrench-outline', 'tools', 'lock-outline', 'key-outline',
  'cog-outline', 'account-group-outline', 'food-outline', 'food-apple-outline',
  'cup-outline', 'coffee-outline', 'beer-outline', 'glass-wine',
  'ice-cream', 'fish', 'pizza', 'egg-outline',
  'bread-slice-outline', 'soccer', 'basketball', 'football',
  'dumbbell', 'run', 'bike', 'swim',
  'tennis', 'golf', 'ski', 'medal-outline',
  'trophy-outline', 'home-outline', 'sofa-outline', 'bed-outline',
  'lamp-outline', 'palette-outline', 'book-outline', 'music-note-outline',
  'headphones', 'television', 'camera-outline', 'gamepad-variant-outline',
  'map-marker-outline', 'earth', 'compass-outline', 'airplane',
  'beach', 'mountain', 'tent-outline', 'city',
  'leaf-outline', 'tree-outline', 'flower-outline', 'weather-sunny',
  'weather-night', 'weather-rainy', 'weather-snowy', 'fire',
  'water', 'lightning-bolt-outline', 'briefcase-outline', 'laptop',
  'wallet-outline', 'file-document-outline', 'calendar-outline', 'clock-outline',
  'clipboard-outline', 'chart-bar', 'bank-outline', 'shopping-outline',
  'cart-outline', 'gift-outline', 'tag-outline', 'store-outline',
  'credit-card-outline', 'bell-outline', 'chat-outline', 'email-outline',
  'phone-outline', 'account-outline', 'heart-outline', 'star-outline',
  'lightbulb-outline', 'magic-staff', 'robot-outline', 'alien-outline',
  'rocket-outline', 'puzzle-outline'
];

export const weekdays = [
  { label: 'Sunday', value: 0 },
  { label: 'Monday', value: 1 },
  { label: 'Tuesday', value: 2 },
  { label: 'Wednesday', value: 3 },
  { label: 'Thursday', value: 4 },
  { label: 'Friday', value: 5 },
  { label: 'Saturday', value: 6 },
];